language: java

jdk:
    - openjdk11

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

after_success:
    - bash <(curl -s https://codecov.io/bash)

script:
    - mvn package verify

after_script:
    - ./cc-test-reporter after-build --coverage-input-type jacoco --exit-code $TRAVIS_TEST_RESULT