language: java

jdk:
    - openjdk11

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - mvn clean verify

after_script:
    - ./cc-test-reporter after-build --coverage-input-type jacoco --prefix /home/travis/build/cbergau/spring_boot_clean_architecture_ddd/report/target/site/jacoco-aggregate --exit-code $TRAVIS_TEST_RESULT